project:
  type: book

book:
  title: "Modern Polars"
  author: "Kevin Heavey"
  favicon: polar-bear-airpods-no-background.png
  cover-image-alt: A drawing of a polar bear wearing airpods
  sidebar: 
    background: "#F5F5F5"
    logo: polar-bear-airpods-no-background.png
    search: true
  repo-url: https://github.com/kevinheavey/modern-polars/
  repo-subdir: book
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  comments:
    giscus:
      repo: kevinheavey/modern-polars

  chapters:
    - index.qmd
    - indexing.qmd
    - method_chaining.qmd
    - performance.qmd
    - tidy.qmd
    - timeseries.qmd
    - scaling.qmd
    - summary.qmd

format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"

# good themes: default, cosmo, flatly, lumen, minty, pulse, sandstone, solar, united
# favourites: minty, cosmo
