project:
  type: book

book:
  title: "Modern Polars"
  author: "Kevin Heavey"
  date: "22/12/2022"
  chapters:
    - index.qmd
    - indexing.qmd
    - summary.qmd

format:
  html:
    theme:
      light: cosmo
      dark: solar
    code-fold: false
    css: custom.css

# good themes: default, cosmo, flatly, lumen, minty, pulse, sandstone, solar, united
# favourites: minty, cosmo

