project:
  type: book

book:
  title: "Modern Polars"
  author: "Kevin Heavey"
  date: "22/12/2022"
  sidebar: 
    background: "#F5F5F5"
  chapters:
    - index.qmd
    - indexing.qmd
    - method_chaining.qmd
    - summary.qmd

format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"

# good themes: default, cosmo, flatly, lumen, minty, pulse, sandstone, solar, united
# favourites: minty, cosmo

